# Generated by Django 5.1.1 on 2024-09-27 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="description",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="title",
        ),
        migrations.AddField(
            model_name="subject",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
